[package]
name = "morph-updater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
morph-rs = { git = "https://github.com/open-morphs/morph-rs", version = "0.1.0" }
